env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
parser: babel-eslint
parserOptions:
  ecmaVersion: 12
rules: {
  indent: [error, 4],
  key-spacing: off,
  no-multi-spaces: off,
  camelcase: off
}
